### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by lucky-lucky** [fengbingchun/Face_Test#1]
能详细说一下使用步骤吗，代码运行错误，不知道怎么改

**Comment by fengbingchun** [comment]
什么错误，可以说具体点吗？哪一个工程？下下来后只要调整下工程属性配置，修改成你本地opencv的真实目录即可，其它均无需改动，或者可以参考下blog: http://blog.csdn.net/fengbingchun/article/category/6488566

**Comment by fengbingchun** [comment]
@lucky-lucky 
什么错误，可以说具体点吗？哪一个工程？下下来后只要调整下工程属性配置，修改成你本地opencv的真实目录即可，其它均无需改动，或者可以参考下blog: http://blog.csdn.net/fengbingchun/article/category/6488566

**Comment by qiang13568** [comment]
你好，我下载了您的工程，也按照要求做了配置，但是为什么结果会提示错误，错误的类型是类里面常量结束时删除错误，由于不能贴错误图片，所以恳请您联系我QQ：285740572，或者留下您的联系方式，我将不胜感激！
