### ISSUE TITLE
代码使用问题，for循环错误

### ISSUE THREAD

**Issue by qiang13568** [fengbingchun/Face_Test#2]
你好，我下载了您的工程，也按照要求做了配置，但是为什么结果会提示错误，错误的类型是类里面常量结束时删除错误。如果检测人脸，那么检测人脸第一张没有问题，也会有绿色的框框住人脸，也正常保存。运行到for循环的第二步就错误了，调试也没有任何的提示，下面既是我项目中的部分问题：
qq：285740572 ，有任何思路或者想法可以联系我，不胜感激，这已经困惑我好几天了

**Comment by qiang13568** [comment]
![image](https://cloud.githubusercontent.com/assets/18524705/20885132/1bf77748-bb2a-11e6-8cf3-8c3dfb85187b.png)

**Comment by qiang13568** [comment]
![image](https://cloud.githubusercontent.com/assets/18524705/20885143/29b0fdc8-bb2a-11e6-8f48-20f3146cf9c3.png)

**Comment by qiang13568** [comment]
![image](https://cloud.githubusercontent.com/assets/18524705/20885212/8a704db2-bb2a-11e6-887a-b6b34e7aeb33.png)
这是项目的属性页面，修改了VC++中的库目录，包含目录；链接器中的附加库目录和附加依赖项。包含了要使用到的所有的lib，include

**Comment by qiang13568** [comment]
![image](https://cloud.githubusercontent.com/assets/18524705/20885336/3b2a2aec-bb2b-11e6-850a-55c7c003c92c.png)
这是楼主给的相应的图片文件，当我运行第一个人脸检测项目的时候，for循环只能运行到第一张图片处理并且保存，之后就会程序崩溃，如下图：
![image](https://cloud.githubusercontent.com/assets/18524705/20885411/a3d7eb56-bb2b-11e6-9967-23a43a12d4f4.png)
运行之后文件夹中的结果如下图所示：
![image](https://cloud.githubusercontent.com/assets/18524705/20885445/c567cf48-bb2b-11e6-9510-3230cda8e486.png)

**Comment by qiang13568** [comment]
程序运行了一个for循环就奔溃了，百度说的是删除了常量或者是什么东西，如果楼主都可以正常运行，为什么我的就会出错，我可以保证环境配置是正确的，因为我之前也测试过seetafaceEngine中的detection模块，可以正常显示测试图片脸的框架。和楼主唯一不同的就是楼主还配置了输出目录，中间目录等，而我没有配置，我的代码如下图：
![image](https://cloud.githubusercontent.com/assets/18524705/20885602/bd6bbec0-bb2c-11e6-9584-6d55d84fd360.png)
箭头所指的地方，第一次可以正常运行，之后继续执行断点代码的时候，按道理会执行第二遍的for循环，结果报错了，错误就是上图

**Comment by fengbingchun** [comment]
@qiang13568  我刚又重新编译运行了seetaface detect程序，一切都正常呀，没有出现你说的情况。如果你不作其它改动，仅改下图像和opencv包括的目录，会报错吗？

**Comment by qiang13568** [comment]
如果仅仅修改图像和包括目录，因为缺少其他库文件，所以不会正常运行，最后我经过调试，发现是程序释放第一次for循环生成的MAT对象时出了问题，，但是楼主的代码最开始我也没做任何更改，释放内存的时候MAT对象有自己的析构函数，应该自己会处理，结果就报错了？MAT类难道不是系统已经写好没问题的吗？我不可能还要去修改它的代码吧 @fengbingchun

**Comment by qiang13568** [comment]
我重新下载你的工程并且运行，在配置的过程中，最后，如果不添加动态dll文件（Identification.dll，FaceDetection.dll，FaceAlignment.dll），运行时候报错，提示缺少，如果添加，则会运行提示另外的错误，请问楼主有没出现提示要求添加dll文件才能运行，我的平台是release，X64，之前也是通过release，X64得到的dll与lib，所以配置的文件属性也是release，X64，
![image](https://cloud.githubusercontent.com/assets/18524705/20918225/df10c04e-bbd0-11e6-9aba-e6d71f4c88d8.png)
![image](https://cloud.githubusercontent.com/assets/18524705/20918232/ea1c8be4-bbd0-11e6-8427-8301042af763.png)

![image](https://cloud.githubusercontent.com/assets/18524705/20918207/c3689358-bbd0-11e6-9c88-145dfdf2da19.png)

![image](https://cloud.githubusercontent.com/assets/18524705/20918177/a5c3c412-bbd0-11e6-9f68-eee7aaac1b19.png)

**Comment by fengbingchun** [comment]
@qiang13568 Mat不需要作任何改动；因为SeetaFaceEngine_Test包括了3个模块的测试代码，所以在配置时需要将三个模块的库都要加上。既然第一个可以检测到人脸并画出框，第二个不可以，我感觉应该是你修改代码导致的。

**Comment by fengbingchun** [comment]
@qiang13568 执行结果：
![image](https://cloud.githubusercontent.com/assets/3479522/20920649/b910f944-bbdb-11e6-850c-951f204adc17.png)

**Comment by qiang13568** [comment]
没修改代码之前就出错，所以尝试了修改代码。最后调试发现，是里面的imread（）函数有问题，我在网上最后找到了解决办法，重新把所有的lib函数完整的加载一遍，问题得到了解决。**感谢楼主的耐心解答，祝好！**另外提醒一句，opencv库中的加后缀-d的是dubug模式的库函数，不带-d的是release模式下的，注意别搞混淆了。 @fengbingchun

**Comment by KellyGodLv** [comment]
@qiang13568 你可以模仿seetafece 源码测试中加载opencv的方式 就不会有那么多问题了
#ifdef _WIN32
#pragma once
#include <opencv2/core/version.hpp>

#define CV_VERSION_ID CVAUX_STR(CV_MAJOR_VERSION) CVAUX_STR(CV_MINOR_VERSION) \
  CVAUX_STR(CV_SUBMINOR_VERSION)

#ifdef _DEBUG
#define cvLIB(name) "opencv_" name CV_VERSION_ID "d"
#else
#define cvLIB(name) "opencv_" name CV_VERSION_ID
#endif //_DEBUG
//opencv库
#pragma comment( lib, cvLIB("core") )
#pragma comment( lib, cvLIB("imgproc") )
#pragma comment( lib, cvLIB("highgui") )
//其他opencv库用到继续添加
//人脸识别库
#pragma comment(lib,"FaceDetection.lib")
#pragma comment(lib,"Identification.lib")

#endif //_WIN32
