### ISSUE TITLE
你好，假如我要识别一个班人的姓名，我改如何入手？

### ISSUE THREAD

**Issue by yongcong1415** [fengbingchun/Face_Test#3]
是不是这样：
1.每个人拍一张图片按名字命名保存；
2.当摄像头读到某个人时就去跟之前保存的所有班的人图片做对比；提出最高分数的那个人；
3.显示最高分数的那个人的名字出来，提示现在的人的名字；

**Comment by fengbingchun** [comment]
@yongcong1415  
1. 保存的不应该是图片，而应该是图片提取的特征
2. 不应该是图片作对比，而是提取的特征作对比
3.应该再设置个阈值
