### ISSUE TITLE
Alignment Performance Analysis

### ISSUE THREAD

**Issue by delta42** [fengbingchun/Face_Test#4]
How do the DLib and libfacedetection compare when it comes to 68-point landmark detection?
Are they the same speed? Do they have the same accuracy?
Thanks.

当涉及到68点地标检测时，DLib和libfacedetection如何进行比较？
他们的速度是否一样？ 他们有相同的准确性吗？
谢谢。

**Comment by fengbingchun** [comment]
@delta42  没有比较过，不过libfacedetection仅支持windows，DLib是跨平台的，DLib中好像仅有正脸检测，但是libfacedetection中对一定角度的侧脸也可以检测到
